---
name: automatic PR for new release

on:
  workflow_dispatch:
    inputs:
      ee-name:
        description: 'EE name'
        required: true
        type: choice
        options:
          - community-ee-base
          - community-ee-minimal
      ansible-core-version:
        description: >-
          Ansible-core version. Example: 2.20.0
        default: latest
  # Run daily (Monday at 08:00 UTC)
  # schedule:
  #   - cron: '0 8 * * *'

jobs:
  build:
    name: 'Build ansible-test images (${{ matrix.name }} with Python ${{ matrix.python }})'
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
