---
name: automatic PR for new release

on:
  workflow_dispatch:
    inputs:
      ee-name:
        description: 'EE name for getting the latest EE version'
        required: true
        type: choice
        options:
          - community-ee-base
          - community-ee-minimal
        default: community-ee-base
      ansible-core-version:
        description: >-
          Ansible-core version. Example: 2.20.0
        default: latest
  # Run daily (at 08:00 UTC)
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    name: 'Update Execution Environment dependencies'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Define ansible-core version
        id: get_version
        run: |
          ANSIBLE_CORE_VERSION=${INPUTS_ANSIBLE_CORE_VERSION}
          if [[ "-${INPUTS_ANSIBLE_CORE_VERSION}" = '-latest' ]]; then
            ANSIBLE_CORE_VERSION=$(curl -sSf "https://pypi.org/pypi/ansible-core/json" | jq -r '.info.version')
          fi
          echo "ANSIBLE_CORE_VERSION=$ANSIBLE_CORE_VERSION" >> "$GITHUB_ENV"
        shell: bash
        env:
          INPUTS_ANSIBLE_CORE_VERSION: ${{inputs.ansible-core-version}}

      - name: Check out ansible-build-data
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          repository: ansible-community/ansible-build-data
          ref: main
          path: ansible-build-data
          persist-credentials: false

      - name: get the latest ansible community version deps file
        working-directory: ansible-build-data
        run: |
          DEPS_FILE=$( find ./ -type f -name ansible-\*\.deps \
            -exec grep -E -l '^_ansible_core_version: '"${ANSIBLE_CORE_VERSION}"'$' {} \; \
          	| while read -r line; do
              ver=$(echo "$line" | sed -n 's/.*ansible-\([0-9.]\+[a-z0-9]*\)\.deps/\1/p')
              tver=$(echo "$ver" \
                  | sed 's/a\([0-9][0-9]*\)/~alpha\1/g' \
                  | sed 's/b\([0-9][0-9]*\)/~beta\1/g'  \
                  | sed 's/rc\([0-9][0-9]*\)/~rc\1/g')
              echo "$tver $line"
          done  | sort -V | sed 's/^[^ ]* //' | tail -n 1 )
          echo "DEPS_FILE=${DEPS_FILE}" >> "$GITHUB_ENV"
        shell: bash

      - name: Update ansible-core and collection versions in all EE Files
        run: |
          COLLECTIONS=''
          touch collections_changed
          git ls-files -- execution-environments/ | grep -E 'execution-environment\.ya?ml$' | while read -r file; do
            echo "File: ${file}"
            yq '.dependencies.galaxy.collections[].name' "${file}" | while read -r key; do
              val=$( grep -E -h "^$key:" ansible-build-data/${DEPS_FILE} | tail -1 | awk '{print $2}' )
              [[ "-${val}" != "-" ]] && \
              yq eval -i --indent 2 ".dependencies.galaxy.collections[] |= select(.name == \"$key\") .version = \"$val\"" "${file}" && \
              echo "- ${key}: \`${val}\`" >> collections_changed || \
              (
                echo "### ⚠️ Collection ${key} not found" | tee -a "$GITHUB_STEP_SUMMARY"
                echo "ansible-build-data/${DEPS_FILE} does not have a collection named $key" | tee -a "$GITHUB_STEP_SUMMARY"
                exit 33
              )
            done
            if [[ $(yq eval '.dependencies.ansible_core.package_pip' "$file" 2>/dev/null) == ansible-core=* ]]; then
              yq eval -i --indent 2 '.dependencies.ansible_core.package_pip = "ansible-core==${ANSIBLE_CORE_VERSION}"' "${file}"
            else
              echo "### ⚠️ lack of ansible-core for ${file}" | tee -a "$GITHUB_STEP_SUMMARY"
              echo "The ${file} does not declare an ansible-core package (no valid 'dependencies.ansible_core.package_pip' ansible-core key)" | tee -a "$GITHUB_STEP_SUMMARY"
            fi
          done
          COLLECTIONS=$(cat collections_changed)

          echo "COLLECTIONS<<EOF" >> $GITHUB_ENV
          echo "$COLLECTIONS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          echo "DIRS=$(git diff --name-only -- execution-environments/ | \
            awk -F '/' '{ print $2 }' | \
            sort -u | \
            awk '{printf "%s%s", sep, $0; sep=", "} END {print ""}' \
          )" >> $GITHUB_ENV
        shell: bash

      - name: Define the new EE version for ${{ env.ANSIBLE_CORE_VERSION }}
        env:
          IMAGE_NAME: ${{ github.repository_owner }}/${{ inputs.ee-name }}
        run: |
          sudo apt install podman --yes
          echo "EE_VERSION=$( \
            podman search --format '{{.Tag}}' \
              --list-tags ghcr.io/${IMAGE_NAME} | \
            grep -- '${ANSIBLE_CORE_VERSION}-' | \
            awk -F'-' '{ if (NF > 1 && $2 ~ /^[0-9]+$/) { print $2 + 1; found=1 } } END { if (!found) print 1 }'
          )" >> "$GITHUB_ENV"
        shell: bash

      - name: Define the new EE version for ${{ env.ANSIBLE_CORE_VERSION }} second
        env:
          IMAGE_NAME: ${{ github.repository_owner }}/${{ inputs.ee-name }}
        run: |
          echo "ANSIBLE_BRANCH_NAME=ansible-core-${ANSIBLE_CORE_VERSION}-${EE_VERSION}" >> "$GITHUB_ENV"

          CI_COMMIT_MESSAGE="${ANSIBLE_CORE_VERSION}-${EE_VERSION}: Update ansible-core and collection versions for ${DIRS}"
          CI_PR_TITTLE="chore: update ansible-core and collection versions for ${DIRS} (${ANSIBLE_CORE_VERSION}-${EE_VERSION})"

          if [[ "-${COLLECTIONS}" = "-" ]]; then
            CI_COMMIT_MESSAGE="${ANSIBLE_CORE_VERSION}-${EE_VERSION}: Update ansible-core version for ${DIRS}"
            CI_PR_TITTLE="chore: update ansible-core for ${DIRS} (${ANSIBLE_CORE_VERSION}-${EE_VERSION})"
          fi
          echo "CI_COMMIT_MESSAGE=${CI_COMMIT_MESSAGE}" >> "$GITHUB_ENV"
          echo "CI_PR_TITTLE=${CI_PR_TITTLE}" >> "$GITHUB_ENV"

        shell: bash

      - name: Checking out to a new branch
        run: |
          git checkout -b "${ANSIBLE_BRANCH_NAME}"

      - name: Setting the user details
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit ansible-build-data and push the changes to github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add execution-environments/**
          git commit -m "${CI_COMMIT_MESSAGE}"
          git branch
          git push origin -f "${ANSIBLE_BRANCH_NAME}"

      - name: Create PR
        id: create-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ASSIGNEE: 'release management team'
        run: |
          body="./pr-body"
          echo -e "This PR updates\n\n- ansible-core: \`${ANSIBLE_CORE_VERSION}\`\n\n" >> "${body}"

          if [[ "-" != "-${COLLECTIONS}" ]]; then
            echo -e "the following collections:\n\n${COLLECTIONS}\n\n" >> "${body}"
          fi

          echo "Triggered by [workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})." >> "${body}"
          echo -n "pr-url=" >> "${GITHUB_OUTPUT}"

          gh pr create \
            --base main \
            --head "${ANSIBLE_BRANCH_NAME}" \
            --title "${CI_PR_TITTLE}" \
            --body-file "${body}" \
            --assignee "${ASSIGNEE}" \
          | tee -a "$GITHUB_OUTPUT"

      - name: Summary
        if: always()
        run: |
          if [ -n "${STEPS_CREATE_PR_OUTPUTS_PULL_REQUEST_NUMBER}" ]; then
            echo "✅ PR #${STEPS_CREATE_PR_OUTPUTS_PULL_REQUEST_NUMBER} created/updated" | tee -a "$GITHUB_STEP_SUMMARY"
            echo "🔗 ${STEPS_CREATE_PR_OUTPUTS_PULL_REQUEST_URL}" | tee -a "$GITHUB_STEP_SUMMARY"
          else
            echo "ℹ️ No changes detected – skipping PR creation" | tee -a "$GITHUB_STEP_SUMMARY"
          fi
        env:
          STEPS_CREATE_PR_OUTPUTS_PULL_REQUEST_NUMBER: ${{ steps.create-pr.outputs.pull-request-number }}
          STEPS_CREATE_PR_OUTPUTS_PULL_REQUEST_URL: ${{ steps.create-pr.outputs.pull-request-url }}
